#!/bin/bash

# Script that runs abTab.

is_win=1

# Unix-style path
lib_path="C:/Users/Reinier/lib/abTab/"

# Create the class path
# NB Instead of creating the class path every time this script is
# called, it can also be created once, in install.sh. However, the
# former is more flexible as it enables addition of code to the 
# class path after installation (and it is very fast anyway (< 0.5s)).
class_path=$($lib_path/cp.sh $lib_path $is_win)
#echo $class_path







# Call java with the arguments given to the script
# NB This command can also be called directly from the CLI
if [ "$1" == "tabmapper" ]; then
    java -cp "$class_path" tabmapper.TabMapper $2 $3 $4
fi