#!/bin/bash

# Script that runs abTab.

code_path="/usr/local/lib/abTab/"

# Create the class path
# NB Instead of creating the class path every time this script is
# called, it can also be created once, in install.sh. However, the
# former is more flexible as it (1) enables addition of code to the 
# class path after installation, and (2) is very fast anyway (< 0.5s)
class_path=$("$code_path""cp.sh" "$code_path")
echo "$class_path" 

## Call java with the arguments given to tabmapper
## NB. This command can also be called directly from the CLI
if [ "$1" == "tabmapper" ]; then
	java -cp "$class_path" tabmapper.TabMapper $2 $3 $4
fi
##	java -cp $("$code_path""cp.sh") tabmapper.TabMapper $1 $2 $3
##java -cp $("$tabmapper_path""cp.sh") tabmapper.TabMapper $1 $2 $3
